### ISSUE TITLE
Deleting Business & User Profiles

### ISSUE THREAD

**Issue by codevonnie** [codevonnie/fourthyearproject#5]
It might be an idea to have an extra authorisation step i.e. reenter email and password if deleting a business or user profile.  User profiles should probably only be able to be deleted from the users app.

**Comment by UnderDev** [comment]
It might be a good idea for a business to be able to delete a person as well, just in case you need to Ban somebody from the company.... Otherwise wed have to ask the person to kindly delete the app themselves.
